package com.example.employeeservice.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;


/**
 * Entity representing an employee within the system.
 * Maps directly to the "employees" table in the database and holds
 * personal, contact, and system metadata details.
 */
@Entity
@Table(name = "employees")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Employee {

    /**
     * Unique identifier for the employee.
     * Automatically generated by the database using the IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title or formal salutation of the employee (e.g., Mr., Ms., Dr.).
     */
    private String title;

    /**
     * Employee's first name. This is a mandatory field.
     */
    @Column(name = "first_name", nullable = false)
    private String firstName;

    /**
     * Employee's last name or surname. This is a mandatory field.
     */
    @Column(name = "last_name", nullable = false)
    private String lastName;

    /**
     * Employee's middle name or patronymic.
     * Kept optional to properly support international citizens.
     */
    @Column(name = "middle_name")
    private String middleName;

    /**
     * Unique email address of the employee.
     * Mandatory field; duplicate emails are strictly prohibited in the system.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * Contact phone number of the employee. This is an optional field.
     */
    private String phone;

    /**
     * Timestamp indicating when the employee record was originally created.
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /**
     * JPA Lifecycle callback that automatically assigns the current timestamp
     * right before the entity is first persisted into the database.
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }
}